# Generated by Django 3.0.3 on 2020-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='subtitle',
            field=models.CharField(default='Something else', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
