# Generated by Django 3.0.3 on 2020-02-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200219_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='subtitle',
            new_name='slug',
        ),
    ]
